[package]
name = "zenith-task"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-queue.workspace = true
anyhow.workspace = true
parking_lot.workspace = true

zenith-core = { path = "../zenith-core" }